language: php
php:
- 5.6
- 7
sudo: false
branches:
  only:
  - master
  - develop
  - release
  - "/^v?[0-9\\.]+/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
install:
- nvm install 6
- npm install -g yarn
- yarn install
- npm rebuild node-sass
before_script:
- openssl aes-256-cbc -K $encrypted_9006bbbd4c7b_key -iv $encrypted_9006bbbd4c7b_iv -in ./.travis/github_deploy_key.enc -out ./.travis/github_deploy_key -d
- mv ./.travis/github_deploy_key ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
script:
- yarn run gulp build
- ls -la style.css index.php assets
before_deploy:
- npm run gulp zip
deploy:
  provider: releases
  api_key:
    secure: Pxn5UYQcN/XpeByMkfmH1AvGAeayKYue91StXXKfGIrfqt2elag5Tni1j/7dm9JEtafX8Y843vqVAJm6eU++o/lvTlm0Hm+SFY4p5Z2Y+xoWUDdfL97aac5jTiBV3nd65hU5Vdx7Iq71NKwUqCzT1iFtHFxNPh1p9ijb0236a0dAs508f+Kgi8nMSlotoAkPcY0pTZp5+Syl7RpwtHbjEBuJ5MYJ8elUrXJbaxiKwPzmiDviznX0XOOXCuKlzjqXeNW43ppMEN7QihlznjGTmNRbPsTwXGT2Grk/sjcg0bzzXSadfIEoSatllEccz8aAczB4SXhJsX9c5tAiYUf61+hiqmgjjo9KkonC7bSqxIK7WYZGMDob0E4SfCU6BgXA3mzcoYj8GJE/ioi5Ds1Bz6oU09YrIvS05ai6+cpo1GLU3SIfntvjDugjDcc+gOj/jHdscfTZDz7JQM41roYF8ipCnEGZqmnptx94EQc+Dm70sHZEae3YjnqBbFGFMxo6v7fTOr8gw/6Cdde5ADQJFfOsdzI3Sc0h4Rw+wFPuYJbSSwXa+ohmXjpQRoeNVLwYn3tfT0xL+wAIJ8Rw9nL43OZutrxiLa/d1uEGF+4DR0BrBFobKQjAdd3zKFH1pcCXsrSjiPqlA9BgfKQ9Cg0I07lvCyt0Ao2XS8enDAmeZas=
  file: earn-pocket-money.zip
  skip_cleanup: true
  on:
    tags: true
    repo: earn-pocket-money/earn-pocket-money
