language: php
php:
- 5.6
- 7
sudo: false
branches:
  only:
  - master
  - develop
  - "/v\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_9006bbbd4c7b_key -iv $encrypted_9006bbbd4c7b_iv -in github_deploy_key.enc -out github_deploy_key -d
install:
- nvm install 6
- npm install -g yarn
- yarn install
- npm rebuild node-sass
script:
- yarn run gulp build
- ls -la style.css index.php assets
after_success:
- bash ./bin/tagging.sh
